name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master  # Trigger the workflow when changes are pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx (optional for multi-architecture builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub (or another registry)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker username stored in GitHub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker password stored in GitHub Secrets

    # Step 4: Build the Docker image
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/house-price-service:latest ./Ex_CICD

    # Step 5: Push the Docker image to the registry
    - name: Push Docker Image to Registry
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/house-price-service:latest

#    # Step 6 (Optional): Deploy to a server or platform
#    - name: Deploy to Server
#      if: success()
#      run: |
#        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_KEY }} user@your-server "docker pull ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest && docker run -d --restart=always -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/house-price-service:latest"
