name: House price estimator CI pipeline

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r Ex_CICD/app/requirements.txt


      - name: Train the model (Online Training)
        run: python model.py


      - name: Run Tests
        run: pytest
  build-and-deploy:
    runs-on: ubuntu-latest

    # ony run if test
    needs: test
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (optional for multi-architecture builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub (or another registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker username stored in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker password stored in GitHub Secrets

      # Step 4: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/house-price-service:latest ./Ex_CICD

      # Step 5: Push the Docker image to the registry
      - name: Push Docker Image to Registry
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/house-price-service:latest

      # Step 6 (Optional): Deploy to a server or platform
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}  # Load the SSH private key from GitHub Secrets

      - name: Deploy to Server
        if: success()
        run: |
          ssh -p ${{ secrets.SERVER_PORT }} -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "docker pull ${{ secrets.DOCKER_USERNAME }}/house-price-service:latest && docker run -d --restart=always -p 8010:5000 ${{ secrets.DOCKER_USERNAME }}/house-price-service:latest"
